name: xbill-xaw
base: core
version: 2.1-xaw.2
summary: Get rid of those Wingdows Viruses!
apps:
  xbill-xaw:
    command: xbill.sh
    plugs: [x11]
    adapter: none
    common-id: xbill.desktop
license: GPL-2.0
description: |
 Ever get the feeling that nothing is going right?  You're a sysadmin, and
 someone's trying to destroy your computers.  The little people running
 around the screen are trying to infect your computers with Wingdows [TM],
 a virus cleverly designed to resemble a popular operating system.  Your
 objective is to click the mouse on them, ending their potential threat. If
 one of the people reaches a computer, it will attempt to replace your
 operating system with the virus it carries. It will then attempt to run
 off the screen with your vital software.
parts:
  xbill:
    plugin: dump
    source: .
    stage-packages:
      - xbill
    organize:
      usr/games/xbill: xbill
      usr/lib/$SNAPCRAFT_ARCH_TRIPLET: libs
      usr/share/xbill/bitmaps: bitmaps
      usr/share/xbill/pixmaps: pixmaps
    stage:
      - xbill.sh
      - xbill
      - pixmaps
      - bitmaps
      - libs

